### ISSUE TITLE
[Win v2.0.0-rc.1] bring icon button back

### ISSUE THREAD

**Issue by Asgatlat** [Lymphatus/caesium-image-compressor#114]
is it possible to add the icon button like the 1.7 version ? 
![image](https://user-images.githubusercontent.com/86599367/167104498-cf3b7fc2-36b6-422a-abdf-3b3e49735e33.png)

**Comment by Lymphatus** [comment]
I was planning on bringing them back but it's a bit more complicated than the past, because the application can have a Light/Dark appearance and the icons should slightly change in color to match.
By the way, I'm not planning to add all the icons as for 1.7. I think some of them are quite useless and not so in line with modern standards.

**Comment by Asgatlat** [comment]
the sweep one is usefull. better than right click and clear list :)
