### ISSUE TITLE
fail to compress 

### ISSUE THREAD

**Issue by 3xploiton3** [Lymphatus/caesium-image-compressor#160]
**Describe the bug**
Fail to compress

**Software version**
The version of Caesium Image Compressor 2.2.1

**Operating System information**
Windows 11

**Screenshots**
![image](https://user-images.githubusercontent.com/19517680/193106146-1d96705d-3c9b-4121-82aa-0670a95cd916.png)

**Comment by 3xploiton3** [comment]
File:
https://file.io/V0Ac0RROah1v

**Comment by Lymphatus** [comment]
I tested the image on the v2.2.1 under macOS (should be the same for Windows) and it compressed, but takes a VERY long time. Depending on the machine it can actually take like 30 minutes to compress. This is an issue with the **lossless** option for PNG only because uses zopfli to compress, which is very slow with large images. This is something I'm trying to address in future versions.

**Comment by Lymphatus** [comment]
Fixed in [v2.3.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.3.0)
