### ISSUE TITLE
Convert HEIC to JPG

### ISSUE THREAD

**Issue by MajorTomDE** [Lymphatus/caesium-image-compressor#169]
**Is your feature request related to a problem? Please describe.**
I use an iPhone and iPad and an Windows notebook. Within the Apple ecosystem I use the HEIC image format.
But when I transfer pictures to Windows and want to send them e.g. to friends, JPG is better for compatibility reasons.

**Describe the solution you'd like**
I know, caesium is primary a compressor and not a converter, but in case auf HEIC it would be great if there is the function:
Convert HEIC to JPG and compress
This would be improve my workflow

**Describe alternatives you've considered**
I tried converter tools but in case of compression caesium is so much better.

**Comment by Lymphatus** [comment]
The major problem with the HEIC format is that is not that well implemented into all platforms. Caesium uses Qt6 and, as you can see from [this table](https://doc.qt.io/qt-6/qtimageformats-index.html), it has native support only on apple operating system. Microsoft started its own support to the format from Windows 10 (via external addons or later patch).
While it might be possible to me to add support for the format to the core library - a request [has already been issued to libcaesium](https://github.com/Lymphatus/libcaesium/issues/14) - it's hard to seamlessly implement it into the UI.

I'll make some experiments after the release of v2.3.0, because HEIC seems a very high requested format to support.

**Comment by Asgatlat** [comment]
+1

**Comment by 7eventech77** [comment]
+1 Would love to have this feature as well in addition to JPG to HEIC.
