### ISSUE TITLE
2.4.0 : can't compress anymore : "check your permissions" error

### ISSUE THREAD

**Issue by Asgatlat** [Lymphatus/caesium-image-compressor#203]
**Describe the bug**
i cannot compress anymore my photos on my nas storage

**Software version**
The version of Caesium Image Compressor 2.4.0

**Operating System information**
 - OS: Windows Pro
 - Version 11 22H2

**Screenshots**
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/86599367/40b588ca-aeb2-4a01-8fe0-0cc3fe5d791e)

**Application Log**
[caesium-2023-05-30.log](https://github.com/Lymphatus/caesium-image-compressor/files/11596779/caesium-2023-05-30.log)

**Comment by Lymphatus** [comment]
Does it work on the 2.3.x version?

**Comment by Lymphatus** [comment]
The bug is caused by the app trying to move the file to trash instead of deleting it right away. This is a new feature in 2.4.0 to allow the user to recover the files even if they are overwritten by the "Same folder as input option". Unfortunately you cannot move to trash files on a NAS Storage, so the app fails there.
I will solve this by trying to trash the files as for now, but if it fails it will just remove it as before.
Nice catch, thanks.

**Comment by Asgatlat** [comment]
2.4.1 fixed the bug, thank you :)
