### ISSUE TITLE
Lossless & output format

### ISSUE THREAD

**Issue by vivadavid** [Lymphatus/caesium-image-compressor#217]
**Describe the bug**
If I add a PNG file, select _Lossless_ and set Output to _JPG_, the file produced by Caesium has a JPG extension, but it's actually a PNG file as shown by MediaInfo or ExifTool.

**Software version**
- Caesium Image Compressor 2.4.1.

**Operating System information**
 - OS: Windows 11 22H2.

**To Reproduce**
1. I add a PNG file.
2. I select _Lossless_.
3. I set Output to _JPG_.

**Expected behavior**
As _Output_ is set to _JPG_, I expect to obtain a JPEG image. For my purposes, I need to get a JPEG file, but I also need, in some circunstances, to get the best quality as possible, and that's why I mark _Lossless_. If there's some kind of contradiction between choosing lossless and converting from PNG to JPEG, maybe Caesium should display some info. In any case, the converted file should have the extension that corresponds to the format it's using.

**Application Log**
[caesium-2023-07-25.log](https://github.com/Lymphatus/caesium-image-compressor/files/12160534/caesium-2023-07-25.log)

**Comment by Lymphatus** [comment]
>  If there's some kind of contradiction between choosing lossless and converting from PNG to JPEG

There is. The two options don't really make sense together, since converting can result in a loss of quality. The example you provided, from PNG to JPG is one of them. I should probably print a warning for this kind of combination, but still the output should always be in the desired format (JPG in your example).
I'll take a look into it.

**Comment by Lymphatus** [comment]
By the way I just tested your scenario and the output from a PNG is a JPG. I checked the fil with `file` on Linux and `MediaInfo `on Windows.

**Comment by vivadavid** [comment]
If turning on _Lossless_ on a PNG implies keeping the format, while I need to convert my image to JPEG, I guess the only thing I could is trying different quality percentages.

Would the opposite make thense? A scenario where I have a JPEG file, I turn on _Lossless_ and I set _Output_ to _PNG_.

**Comment by Lymphatus** [comment]
If you select an output format different from the original the app does something like this:
- Converts the image to the new format using the maximum quality possible (100). Note that this can still mean that you can lose quality, regardless of the compression option selected. Think of a PNG with transparent background converted to JPG, the transparent pixels will be black.
- If lossless is not selected, it will compress to the desired quality
- If lossless is selected, it will just try to shave some size applying a lossless compression

Converting a JPG to a PNG will preserve the image as is, even though it will probably increase in size. The opposite is not true, because JPG is lossy by default and just the PNG -> JPG process will degrade the image, even so slightly.

Hope is more clear, feel free to ask anything else if you still have doubts.

**Comment by vivadavid** [comment]
Hi, @Lymphatus ,

Thank you for the explanation.

Despite not making much sense and despite the loss of quality, I think it'd still be nice if Caesium could apply lossless to a PNG image that could be converted to a JPEG. I'm thinking about a context where you absolutely need a JPEG as output but, at the same time, you want to get the best possible quality within some limits.

**Comment by Lymphatus** [comment]
For the PNG -> JPG Caesium already performs a conversion with 100 quality applied and _then_ goes for lossless optimization. Since the quality difference in the range 80-100 is usually very minimal, going for lossless after a conversion - in my personal opinion - will just give you a bigger image without any real gain in quality. It's counterintuitive, but converting PNG -> JPG with quality 80-90 can achieve very similar result as lossless with much much smaller image.

You can do some tests and see by yourself what's the best tradeoff for you.

**Comment by vivadavid** [comment]
In that case, I'll do that. Thanks, @Lymphatus !

**Comment by vivadavid** [comment]
Hi,

Sorry that I've reopened the thread, but I wanted to test the issue on 2.5.0.

Despite not being recommended, I've tried to convert a PNG file with _Lossless_ on, _Skip if output size is bigger than original_ on and _Output_ set to _JPG_. The results seem contradictory:

1. I get a message saying _Compression finished_.
2. On the _Info_ field, I get a message saying _Skipped: compressed file is bigger than the original_.
3. In file explorer, there's actually a new JPEG file, so the conversion was completed.
4. The JPEG file is still a PNG, as shown by Mediainfo or ExifTool.
5. The converted file has the same date as the original despite _Keep file dates_ being off. Edited: I've just hashed both files and they are exactly the same, except for the wrong extension of the converted image.

[caesium-2023-08-08.log](https://github.com/Lymphatus/caesium-image-compressor/files/12294555/caesium-2023-08-08.log)
