### ISSUE TITLE
Convert JPG/supported format to PDF

### ISSUE THREAD

**Issue by 7eventech77** [Lymphatus/caesium-image-compressor#255]
**Is your feature request related to a problem? Please describe.**
The problem is outside of Adobe Acrobat which works okay when converting images to PDFs for annotating, the organization I work for uses a tax software of which clients send in tax documents as images that need to be converted to PDF for annotating. These tax documents need to have these annotations easily removed instead of being merged into the image. Adobe Acrobat imports it but instead saves it to a tempfile in AppData folder which defeats the point and not the folder where the original image is stored. In addition, these images are sometimes are buried 10-15 folders deep with random number/letter names so it is a pain to try and find the folder where these images are saved to. It causes unneeded time spent trying to convert each one by hand after finding them. I know Caesium has a "same folder as input" function which would work well for saving the files in the same folder as the images which would be deleted after the fact. As described below, ImageGlass (Our default image viewer) connects beautifully to Caesium via tools and passes the image directly into Caesium to convert whereas other software I have tried does not.  This feature would also help anyone that doesn't pay for Adobe Acrobat or similar service to convert images into PDFs to be to annotate or edit them.

**Describe the solution you'd like**
I would like to be able to convert JPGs primarily /any other supported format to a PDF as an "image" in the JPG format (since that is really the only good PDFs support for images that I know of.) PDF to JPG is not necessary as I don't see myself or my workplace using it but it is not much extra work then might as well have it as an option for anyone who needs it.

**Describe alternatives you've considered**
I have tried the software "Converseen" that does convert images to PDFs but does not import an image from ImageGlass 9 through its "tools" function. I have also tried a new "4K Image Compressor" that does not support converting to PDFs yet but it does not import the image into it's queue either from ImageGlass. Caesium for whatever reason is able to import images from ImageGlass with no issues and able to compress/convert quite easily out of the box once the file path is added to the .exe. 

**Additional context**
If this request is outside of the scope of Caesium, I understand. If anything, any help pointing in a direction to go to solve this annoying issue would be appreciated. I will be trying to contact the developer of ImageGlass to see if they can add an option to "save as PDF" from an image as well.

Thank you for your consideration in advance! I really enjoy your software and its UI compared to others I have used.

**Comment by Lymphatus** [comment]
Unfortunately, conversion to PDF is very out of scope of Caesium. The main goal of this software is to compress images, while also supporting basic conversion between supported formats. The main issue with PDF, other than it's not an image file, is that is a very difficult format to manipulate. So I cannot provide support for JPEG to PDF into Caesium, but you have alternatives.

I'm not familiar with ImageGlass, but I think they integrate well is because Caesium can accept files to compress "directly". If you drag and drop files to the Caesium icon on your Desktop (or wherever it is), you'll see it will automatically import them. There's also an option to import and compress by doing so. Another method is to call Caesium from the commmand line (CMD in Windows) with the list of files to compress and will behave the same. This is probably how ImageGlass integrates.

For your specific need, you can probably use [ImageMagick](https://imagemagick.org/index.php) which is a very well known and capable software. It has a very handy tool called `convert` which can convert images to PDF. The full documentation is [here](https://imagemagick.org/script/convert.php), but it's a little technical. I'm pretty sure you can achieve what you want with that.
I'm not really familiar with other solutions, this is what I used when I needed a PDF from an image, but was rarely the case.

Hope I helped!

**Comment by 7eventech77** [comment]
Thank you for your help! I kind of figured it might be out of project scope but figured I would ask anyway. I really enjoy your software and the UI, just wish it supported more formats such as (HEIC, JPGXL, AVIF etc.) and then it would be perfect. But I understand that there are certain limitations that may take time to change. Thank you!
