### ISSUE TITLE
Program Width Too Large Causing Usability Issues

### ISSUE THREAD

**Issue by agungsan147** [Lymphatus/caesium-image-compressor#307]
**Is your feature request related to a problem? Please describe.**
I'm having difficulty using the program because the width is too large.

**Describe the solution you'd like**
I want the width of the program to be reduced again.
![Capturedawf](https://github.com/user-attachments/assets/ceadf5e4-82cb-45ef-aad7-c120e9207700)

**Comment by 7eventech77** [comment]
Having this same issue as well with my Surface Go 2 since the latest update to 2.7

**Comment by Lymphatus** [comment]
In [43aa740](https://github.com/Lymphatus/caesium-image-compressor/commit/43aa74016e125367637c8744bddc163fc3dbcc87) I made so the application can be reduced to a minimum width of 800px. Also made the side panel collapsible, to have more space for the list on the left. Should solve your issue I guess.

**Comment by agungsan147** [comment]
I think 800px is too wide. How do I collapse the side panel?

Thank you :)

![image](https://github.com/user-attachments/assets/e9347147-b9a7-4074-9e6b-c1db5759469e)

**Comment by 7eventech77** [comment]
> In [43aa740](https://github.com/Lymphatus/caesium-image-compressor/commit/43aa74016e125367637c8744bddc163fc3dbcc87) I made so the application can be reduced to a minimum width of 800px. Also made the side panel collapsible, to have more space for the list on the left. Should solve your issue I guess.

I am okay with 800px since I don't have any devices with less than a 1080p screen, but for anyone who has a device with a screen resolution of less than 1600×900 then they won't be able to snap the application to half the screen which I like to do. 1366×768 is really the only "common" resolution for screens now, mainly used on budget laptops. Most everything else is 1920x1080 or similar if different aspect ratio. 

The other thing to consider is for Windows tablets like Microsoft's Surface series or a 2 in 1. For example, on my Surface Go 2's 1920x1280 screen it would potentially be better for the right panel to be below the left panel instead of the right since it is slightly smooshed together. Of course the other option is to collapse/hide the left panel when the window size becomes too small since both panels don't have to be used at the same time.

**Comment by Lymphatus** [comment]
Totally understand the issue. In 5fa7a8a53825ec4b760f834fd543054b8b2e42db I made the minimum size of the window to 500x500px. I don't think the app would the usable with less space than that, especially in height.
The right panel (the one with the compression options) can be collapsed, so you can set your options, hide it and just focus on the list.
@agungsan147 those options will be available once I publish the new version.

**Comment by 7eventech77** [comment]
500x500 sounds good, thank you!
