### ISSUE TITLE
[bug]will skip files in folders which name contains other set of characters

### ISSUE THREAD

**Issue by acios** [Lymphatus/caesium-image-compressor#31]
When you put a folder with subfolders in, it can recognize all the files, but all files within subfolders which have other characters on the name will not be converted (in my case Chinese)

My guess is that it might have problem creating new folder with the same name

Please fix, thanks

**Comment by Lymphatus** [comment]
Can you provide an example? Which version are you using?

**Comment by acios** [comment]
I'm using 2.2.0 alpha, within a folder with multiple sub-folders, it skipped every folder with a Chinese name.
Version 1,7.0 processed all the folders although.

**Comment by Lymphatus** [comment]
I tried with some (random) Chinese characters without issues on the newest alpha version. Can you provide me some example names (or folder structure) that's giving you trouble so I can try to replicate?

Also, which Operating System are you using?

**Comment by Miraihi** [comment]
Right, I have the same problem with Cyrillic script.

**Comment by Lymphatus** [comment]
Thanks @Miraihi, I'm going to take a run with those characters. Maybe it's an issue with the Windows environment, my tests on the OS X machine were fine with Chinese chars. I'll report back.

**Comment by Lymphatus** [comment]
Can confirm it's a Windows specific issue. I'm gonna take a look into it for the next release.

**Comment by Lymphatus** [comment]
UPDATE
The problem is related to every non-ASCII character in Windows. Unfortunately, the libraries powering Caesium are not fully compatible with unicode charset, so there's no _real_ solution to this.
On the bright side, as a workaround, you can enable Unicode support globally on Windows going to

> All Settings -> Time & Language -> Language -> "Administrative Language Settings"

and checking the Beta: UTF-8 support.
I tested it and worked just fine after a reboot. It's not the best solution, but works.

**Comment by Miraihi** [comment]
Thank you, I appreciate your efforts!
