### ISSUE TITLE
can't select the option to maintain the aspect ratio

### ISSUE THREAD

**Issue by JAYJAYALLEN** [Lymphatus/caesium-image-compressor#324]
![image](https://github.com/user-attachments/assets/b724fd5e-b3d2-4d7e-872b-d69122ed3c93)

I can't select the option to maintain the aspect ratio.

**Comment by Lymphatus** [comment]
Keep aspect ratio is disabled for every option except for the "Percentage" resize mode. Let me explain a little bit more:

- Dimensions: it is disabled because you can select the exact sizing yourself and having full control
- Percentage: here you can select/deselect the option
- Others: the other options will always keep aspect ratio, because they are resizing just by one dimension
In you example, you are resizing by "short edge" (hope I got the translation right) and so it will always keep the ratio not matter what.
The UI is a bit confusing because the option is deselected, so it seems it's not working.
