### ISSUE TITLE
Chocolatey

### ISSUE THREAD

**Issue by robsonsobral** [Lymphatus/caesium-image-compressor#39]
Hi!

Can you, please, consider to make Caesium available on [Chocolatey](https://chocolatey.org/)?

@teknowledgist already did it an unofficial version. Maybe it can be linked to release process.

Thank you!

**Comment by Lymphatus** [comment]
For sure not in alpha stage, as it's way too early. I think I will evaluate package managers during the beta and for sure for the stable release.

**Comment by teknowledgist** [comment]
I am happy to help with [the Chocolatey package](https://chocolatey.org/packages/caesium.install), but when you are ready, I recommend [identifying yourself as the author](https://chocolatey.org/docs/package-triage-process#i-want-to-take-overhelp-with-package-maintenance-for-my-software) because that has some benefits (e.g. automatically makes the package "trusted").

**Comment by teknowledgist** [comment]
Just FYI, I updated and submitted [the v2.0.0-beta4 package](https://community.chocolatey.org/packages/caesium.install/2.0.0-beta4).  I don't know if it will pass automated verification however because the application auto-opens after a *silent* install.  Can that be stopped?

**Comment by Lymphatus** [comment]
The only silent install was on update, but I removed that behaviour (it's a configuration on the update server). Now opens a prompt and you need to actually do some actions, so it should work. Or am I missing something?

**Comment by teknowledgist** [comment]
I'm the one who must be missing something, because I don't really understand what you just said.  😄 

I do know is that `caesium-image-compressor-2.0.0-beta.4-win-setup /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-` requires no additional interaction from the user on a clean machine except that it starts the application when finished.  I wasn't updating and no server was involved.

**Comment by Lymphatus** [comment]
Was my fault, I was confusing the install options you are using with the one that I use for the auto update system (they are pretty similar).
I saw all checks passed, so probably not an issue, but you can use `/SILENT` instead of `/VERYSILENT` and it will open the InnoSetup dialog with the progress bar.

Speaking of taking ownership of the package, we are getting close to the stable release. There'll probably be just a Release Candidate.
I'm very very new to Chocolatey (I'm a MacOS user for quite a few years now) but I'm going to have a deep look at the docs.
Of course, thanks for your contribution.

**Comment by Lymphatus** [comment]
@teknowledgist I sent you a message on Chocolatey. The 2.0.0 stable version is out, so I think I can start to maintain the chocolatey package.
Let me know if you need futher info by my side.
Thanks!

**Comment by teknowledgist** [comment]
@Lymphatus Assuming your Chocolatey username is the same, I just added you as a maintainer.  You can leave me on or remove me -- your choice.  As I mentioned before, I believe there may be an advantage to notifying the admins that you are also the author.

I will disable automatic updates and, eventually, remove the code in my repo for the package so as not to confuse things.

Let me know if I can help with anything.
