### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DillFrescott** [Lymphatus/caesium-image-compressor#43]
I know its called an image compressor, but if you could have a ffmpeg section to slim down video that would be absolutely fantastic.

Because at the moment, I have to use a separate program to compress videos. It would be awesome to be able to do it alongside all the images in Caesium.

Just the standard filters, video settings, and audio bitrate would be fine. I always set the crf to around 24 on fast to shed off some of the extra data.

**Comment by Lymphatus** [comment]
Unfortunately, video compression is a very different topic and worth a software by itself. I'm quite confident I won't add this option for the 2.0.0 version, since it would require a lot of extra work (and I should rename the software!). 

So I'm closing this because it won't happen in the near future and probably never. My apologizes.

**Comment by DillFrescott** [comment]
It's okay. Was worth asking I guess haha. I totally understand!
