### ISSUE TITLE
Batch Resize based on Width and auto height

### ISSUE THREAD

**Issue by Dedi-Data** [Lymphatus/caesium-image-compressor#58]
Thank you for this great application

I think it is great if you implement the way to set width in a value and set height to auto (Keep Aspect Ration) and vise versa in batch mode
in this way we can set maximum value for width or height while we keep the aspect ratio for all images

Thank you so much
Regards

**Comment by Lymphatus** [comment]
You can already achieve this, by selecting "_Long/Short Edge_" as a resize option. If you tick the "_Do not enlarge_" option too, it won't scale up any image, just down the ones that are larger.

**Comment by Hubvill** [comment]
Where are the "Long/Short Edge" options? See image bellow what my Caesium looks like
![ss](https://user-images.githubusercontent.com/10275529/152660342-5cbccdd9-5025-4cda-b33a-6cab87d91961.png)
.

**Comment by BigBoyBarney** [comment]
The resize option doesn't actually scale the images up (even if the "Do not enlarge" option is not enabled). The image size stays the same. If I enter a size lower than the original image size, it scales down correctly

**Comment by wjdob** [comment]
This does not work well when photos are mixed orientation. It will then scale up to either the long or short edge. Similar problem happens when using other resize modes.
Orientation detection would be beneficial, and ability to set standard resolutions as preset (for example - resize down to 1920x1080 or a specific ratio, no upscale, keep orientation).
Simple solution would be to check whichever dimension number is greatest before resizing. The greater number would be set as "long". If the number is already too small, skip, otherwise scale to percentage or specific number keeping the aspect ratio.
