### ISSUE TITLE
no option to change language (V 2.0.0 Alpha 4)

### ISSUE THREAD

**Issue by Asgatlat** [Lymphatus/caesium-image-compressor#61]
hi,

in the program files there is a translation folder but in the program there is no option to change language

**Comment by Lymphatus** [comment]
Yes, you can't actually change the language right now. The translation folder is there because there's an Italian and English translation, but the Italian one is automatically set only of your current system language is IT.

The option to switch language will come in the near future with an update, it's on schedule.

**Comment by Lymphatus** [comment]
You can now change the language in the alpha.5 release. Only EN and IT are currently available.
