### ISSUE TITLE
Where did the Russian translation go?

### ISSUE THREAD

**Issue by mrkaban** [Lymphatus/caesium-image-compressor#76]
Hello, was there a Russian translation in the previous version? where did he go? need help translating strings?

**Comment by Lymphatus** [comment]
Hi! All the translations in the previous version (except for Italian, since it's my first language) aren't usable anymore, because this is a complete code rewrite of the first release.
You can help translating if you want - and I'll be very thankful!

If you want a place to start, have a look at #57, which is a Chinese translation.

I'll publish detailed instruction of how to contribute to the project, but if you need help or direction I can give you some tips here.

**Comment by mrkaban** [comment]
Everything is very difficult. Opened a ticket, where are the files for translation? It does not indicate where to get them, there is immediately import of its code. Just give the files or lines to translate.
