### ISSUE TITLE
Linux package (deb,rpm, ...)

### ISSUE THREAD

**Issue by alkaphreak** [Lymphatus/caesium-image-compressor#82]
As the title said, why not provide linux binaries and packages, at least for the CLI version.

**Comment by Lymphatus** [comment]
I just started testing the linux version since beta and the libcaesium library was not really ready to be shipped on Linux. I will try to make up something in the next days, at least for Ubuntu.

Also, i wanted to focus first on Windows, which has the most userbase, and Mac, which is my work environment. Just convenience.

**Comment by alkaphreak** [comment]
Previously i was able to build the lib and the cli but lastly it was impossible without hard work.

Thanks for your support :)

**Comment by Lymphatus** [comment]
Libcaesium should be easier now, since it's just a Rust library. I'd also like to convert the CLI tool to Rust and make it easier to compile and ship to package managers.

**Comment by alkaphreak** [comment]
Ho nice. Wasn't aware of your Rust migration.

**Comment by alkaphreak** [comment]
Will give a try soon then. Thanks again for your hard work.
